# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os $username $directory$git_branch$git_status$character"""

# Drop ugly default prompt characters
[character]
success_symbol = '[➜ ](bold green)'
error_symbol = '[✗ ](bold red)'

# ---

[os]
format = '[$symbol](bold green)'
disabled = false

[os.symbols]
Windows = '  '
Arch = '󰣇 '
Ubuntu = ' '
Macos = '󰀵 '

# Shows the username
[username]
style_user = 'bold green'
style_root = 'bold yellow'
format = '[ubuntu]($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow) '
disabled = false

# Shows current directory
[directory]
style = 'bold blue'
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '
